{"start-date": "2016/6/20", "end-date": "2016/6/21", "country": "Japan", "desc": "At least six people died and one was missing on 22 June 2016 as record-breaking rains battered parts of southwestern Japan still reeling from earthquakes two months ago, setting off flooding and landslides. "}
{"start-date": "2018/7/5", "end-date": "2018/7/11", "country": "Japan", "desc": "Dozens of people have died and at least 50 are missing after torrential rain triggered landslides and flash flooding in western Japan on Saturday.Local authorities said 20 people had been killed, while public broadcaster NHK said the death toll had risen to 46. "}
{"start-date": "2019/8/28", "end-date": "2019/8/29", "country": "Japan", "desc": "Torrential rain hit southwestern Japan on 28 August 2019, prompting local and prefectural governments to instruct hundreds of thousands of people to evacuat. "}
{"start-date": "2020/6/29", "end-date": "2020/7/5", "country": "Japan", "desc": "The death toll from floods and landslides caused by heavy rain in Kumamoto Prefecture, southwestern Japan, has reached 16. Authorities say 17 other people have no vital signs and 13 are missing. "}
{"start-date": "2016/6/20", "end-date": "2016/6/21", "country": "Japan", "desc": "At least six people died and one was missing on 22 June 2016 as record-breaking rains battered parts of southwestern Japan still reeling from earthquakes two months ago, setting off flooding and landslides. "}
{"start-date": "2016/6/20", "end-date": "2016/6/21", "country": "Japan", "desc": "At least six people died and one was missing on 22 June 2016 as record-breaking rains battered parts of southwestern Japan still reeling from earthquakes two months ago, setting off flooding and landslides. "}
{"start-date": "2018/7/5", "end-date": "2018/7/11", "country": "Japan", "desc": "Dozens of people have died and at least 50 are missing after torrential rain triggered landslides and flash flooding in western Japan on Saturday.Local authorities said 20 people had been killed, while public broadcaster NHK said the death toll had risen to 46. "}
{"start-date": "2019/8/28", "end-date": "2019/8/29", "country": "Japan", "desc": "Torrential rain hit southwestern Japan on 28 August 2019, prompting local and prefectural governments to instruct hundreds of thousands of people to evacuat. "}
{"start-date": "2020/6/29", "end-date": "2020/7/5", "country": "Japan", "desc": "The death toll from floods and landslides caused by heavy rain in Kumamoto Prefecture, southwestern Japan, has reached 16. Authorities say 17 other people have no vital signs and 13 are missing. "}
{"start-date": "2016/6/20", "end-date": "2016/6/21", "country": "Japan", "desc": "At least six people died and one was missing on 22 June 2016 as record-breaking rains battered parts of southwestern Japan still reeling from earthquakes two months ago, setting off flooding and landslides. "}
{"start-date": "2018/7/5", "end-date": "2018/7/11", "country": "Japan", "desc": "Dozens of people have died and at least 50 are missing after torrential rain triggered landslides and flash flooding in western Japan on Saturday.Local authorities said 20 people had been killed, while public broadcaster NHK said the death toll had risen to 46. "}
{"start-date": "2019/8/28", "end-date": "2019/8/29", "country": "Japan", "desc": "Torrential rain hit southwestern Japan on 28 August 2019, prompting local and prefectural governments to instruct hundreds of thousands of people to evacuat. "}
{"start-date": "2020/6/29", "end-date": "2020/7/5", "country": "Japan", "desc": "The death toll from floods and landslides caused by heavy rain in Kumamoto Prefecture, southwestern Japan, has reached 16. Authorities say 17 other people have no vital signs and 13 are missing. "}
{"start-date": "2016/6/20", "end-date": "2016/6/21", "country": "Japan", "desc": "At least six people died and one was missing on 22 June 2016 as record-breaking rains battered parts of southwestern Japan still reeling from earthquakes two months ago, setting off flooding and landslides. "}
{"start-date": "2018/7/5", "end-date": "2018/7/11", "country": "Japan", "desc": "Dozens of people have died and at least 50 are missing after torrential rain triggered landslides and flash flooding in western Japan on Saturday.Local authorities said 20 people had been killed, while public broadcaster NHK said the death toll had risen to 46. "}
{"start-date": "2019/8/28", "end-date": "2019/8/29", "country": "Japan", "desc": "Torrential rain hit southwestern Japan on 28 August 2019, prompting local and prefectural governments to instruct hundreds of thousands of people to evacuat. "}
{"start-date": "2020/6/29", "end-date": "2020/7/5", "country": "Japan", "desc": "The death toll from floods and landslides caused by heavy rain in Kumamoto Prefecture, southwestern Japan, has reached 16. Authorities say 17 other people have no vital signs and 13 are missing. "}
